"""Update column types for users table

Revision ID: 1357e8261498
Revises: 68eb10d40dd7
Create Date: 2024-06-27 04:41:02.292525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1357e8261498'
down_revision: Union[str, None] = '68eb10d40dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.String(length=320),
                    type_=sa.Text(),
                    existing_nullable=False)
    op.alter_column('users', 'fullname',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.Text(),
                    type_=sa.String(length=320),
                    existing_nullable=False)
    op.alter_column('users', 'fullname',
                    existing_type=sa.Text(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=False)
    # ### end Alembic commands ###
