"""Baseline schema

Revision ID: 68eb10d40dd7
Revises: ad33d299cedc
Create Date: 2024-06-26 00:46:35.568154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eb10d40dd7'
down_revision: Union[str, None] = 'ad33d299cedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.create_table('state_data',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('State', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('Lga', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Ward', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Village', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Estimated_Christian_Population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Estimated_Muslim_Population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Estimated_Traditional_Religion_Population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Converts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Estimated_Total_Population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Film_Attendance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('People_Group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Practiced_Religion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='state_data_pkey')
    )
    op.create_index('ix_state_data_Lga', 'state_data', ['Lga'], unique=False)
    op.create_table('volunteer',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('volunteer_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='volunteer_pkey')
    )
    op.create_table('links',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    op.create_index('ix_links_url', 'links', ['url'], unique=True)
    op.create_index('ix_links_media_type', 'links', ['media_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
