"""Remove visibility column from blogs table

Revision ID: 8ffed2bbea21
Revises: 9002e7d55847
Create Date: 2024-08-10 16:53:07.453882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffed2bbea21'
down_revision: Union[str, None] = '9002e7d55847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('visibility', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
