"""modified discipleship and filmshow table model

Revision ID: 96fe904d3f2d
Revises: 9e9bfee9edc0
Create Date: 2024-08-26 00:39:27.162876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fe904d3f2d'
down_revision: Union[str, None] = '9e9bfee9edc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
