"""Initial migration

Revision ID: ad33d299cedc
Revises: 
Create Date: 2024-06-08 07:59:40.282076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad33d299cedc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_media_type'), 'links', ['media_type'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=True)
    op.create_table('state_data',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('State', sa.Enum('Abia', 'Adamawa', 'AkwaIbom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross_River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara', name='states'), nullable=False),
    sa.Column('Lga', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Ward', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Village', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Estimated_Christian_Population', sa.Integer(), nullable=False),
    sa.Column('Estimated_Muslim_Population', sa.Integer(), nullable=False),
    sa.Column('Estimated_Traditional_Religion_Population', sa.Integer(), nullable=False),
    sa.Column('Converts', sa.Integer(), nullable=False),
    sa.Column('Estimated_Total_Population', sa.Integer(), nullable=False),
    sa.Column('Film_Attendance', sa.Integer(), nullable=False),
    sa.Column('People_Group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Practiced_Religion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_data_Lga'), 'state_data', ['Lga'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('volunteer',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volunteer_email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    op.drop_table('users')
    op.drop_index(op.f('ix_state_data_Lga'), table_name='state_data')
    op.drop_table('state_data')
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_media_type'), table_name='links')
    op.drop_table('links')
    op.drop_table('contact')
    # ### end Alembic commands ###
