"""modified discipleship and filmshow table model

Revision ID: e69b560d6ab4
Revises: 96fe904d3f2d
Create Date: 2024-08-26 01:16:51.580906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69b560d6ab4'
down_revision: Union[str, None] = '96fe904d3f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
